### ISSUE TITLE
(feat) Fill service catalog table with service entries.

### ISSUE THREAD

**Issue by hastebrot** [hastebrot/htmx-playground#12]
| original estimate | estimate | actual effort | remaining effort |
|--|--|--|--|
| 2h | 4h30m | 4h | 0h |

**acceptance criteria:**
- we have a JSON endpoint that gives us service entries
- the data model has enough fields to fill the table (static mockup)

**task breakdown:**
- [x] `monitoring-data`, add service with `postgres` library, `model.ts` with endpoint messages and `Service` message, `client.ts` with `ServiceStoreClient`, and `api.ts` with `/write-service` and `read-services` JSON-endpoints [1h]
- [x] `monitoring-test`, add tests for the new JSON-endpoints, i.e. `/write-service` and `/read-services` [30m]
- [x] `monitoring-test`, add tests for the HTML-endpoints, i.e. `/` (index), `/layout`, `/page/service-catalog` [30m]
- [x] `monitoring-site`, extract components for field value states, and prepare data fixtures with useful field values [2h]
- [x] create, review, merge pull request; developer and testing instructions [30m]

**technical details:**
- we need to refactor the `monitoring-site` table into components specific to the service data
- test cases in `monitoring-test` service call write and read endpoints to create data fixtures
- starred services are user-specific, in a later story we need a story for this endpoint. for this story, just create random `isStarred` values
- sort the table by service name by default, we can do it in the endpoints in `monitoring-data`
- go with a test-driven approach with data fixtures and html DOM tested with `fetch()` and https://github.com/WebReflection/linkedom

**out of scope:**

**Comment by hastebrot** [comment]
Closed by #13 and #14
